version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - blog-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  redis:
    image: redis:5-alpine
  web:
    build: .
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DB_HOST: "db"
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_URL: "redis://redis:6379/0"
      GIPHY_API_KEY: "${GIPHY_API_KEY}"
    depends_on:
      - db
      - redis
  jobs:
    build: .
    volumes:
      - .:/blog
    command: bundle exec sidekiq
    environment:
      DB_HOST: "db"
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_URL: "redis://redis:6379/0"
      GIPHY_API_KEY: "${GIPHY_API_KEY}"
    depends_on:
      - db
      - redis
volumes:
  blog-postgres:

