version: '3'
services:
  db:
    image: postgres:10-alpine
  redis:
    image: redis:5-alpine
  web:
    build: .
    volumes:
      - .:/blog
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "production"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
